apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -internal
commonLabels:
  app.kubernetes.io/name: bos-gateway
  app.kubernetes.io/component: bos
  app.kubernetes.io/instance: internal
resources:
  - ../../../../base-0.0.0
  - certificate.yaml
  - frontend-config.yaml
  - ingress.yaml
configMapGenerator:
  - literals:
      - NEXT_PUBLIC_NETWORK_ID=testnet
      - NEXT_PUBLIC_HOSTNAME=https://internal.calimero.network
      - NEXT_PUBLIC_CHAIN_ID=testingshard-calimero-testnet
      - NEXT_PUBLIC_RPC_ENDPOINT=https://api.staging.calimero.network/api/v1/shards/testingshard-calimero-testnet/neard-rpc/
      - NEXT_PUBLIC_WALLET_URL=https://mnw-calimero-staging-testnet.netlify.app/
    name: bos-gateway
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
